### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
### code here
import numpy as np

In [2]:
arr = np.array([[3, 2, np.nan, 1],[10, 12, 10, 9],[5, np.nan, 1, np.nan]])

print("Original array:\n",arr)
print("\nFind the missing data of the said array:\n" ,np.isnan(arr))

Original array:
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [ ]:
### code here 

In [14]:
arr1 = np.array([0.2,2.4,1.3])
arr2 = np.array([0.299999,2.400000,1.300000])
print("original arrays:",arr1,arr2, sep='\n')
print("\ncheck whether two array are equal (element wisw) or not:")
print(arr1==arr2)

arr1 = np.array([0.3,1.4,2.3])
arr2 = np.array([0.344444,1.40001,2.3])
print("\noriginal array:",arr1,arr2,sep="\n")
print("\ncheck whether two array are equal (element wise) or not:")
print(arr1==arr2)

original arrays:
[0.2 2.4 1.3]
[0.299999 2.4      1.3     ]

check whether two array are equal (element wisw) or not:
[False  True  True]

original array:
[0.3 1.4 2.3]
[0.344444 1.40001  2.3     ]

check whether two array are equal (element wise) or not:
[False False  True]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [ ]:
## code here

In [25]:
arr = np.arange(0,16).reshape(4,4)
print("Original array:\n", arr)
print("\nNew array after swapping first and last rows of the said array:")
print(arr[::-1])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [ ]:
#### code here

In [29]:
my_list = [1,2,3,4,5,6,7,8,9,10]
print("List to array:\n",np.asarray(my_list))

my_tuple = ([5,6,4,2],[2,7,9,7])
print("\nTuple to array:\n",np.asarray(my_tuple))

List to array:
 [ 1  2  3  4  5  6  7  8  9 10]

Tuple to array:
 [[5 6 4 2]
 [2 7 9 7]]


###### 5. Write a NumPy program to find common values between two arrays.

In [ ]:
### code here

In [31]:
x = np.array([2,4,6,8,3])
y = np.array([4,8,3])
print("common values between two arrays:")
print(np.intersect1d(x,y))

common values between two arrays:
[3 4 8]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [ ]:
### code here

In [46]:
x = np.arange(1,7).reshape(3,2)
print("Reshape 3x2:\n",x)
print("\nReshape 2x3:\n",x.reshape(2,3))

Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Reshape 2x3:
 [[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [ ]:
### code here

In [71]:
x = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
print("Original array:\n",x)
y = np.unique(x,return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((y)))

Original array:
 [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [ ]:
### code here

In [80]:
x = np.array([[0,0,0],[1,2,3],[4,5,6]])
print("Original arrays:\nArray-1\n",x)
y = np.array([10,11,12])
print("Array-2\n",y)

arr2 = x + y
print("\nNew Array:\n",arr2)

Original arrays:
Array-1
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
 [10 11 12]

New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

In [81]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [ ]:
## code here

In [88]:
x = np.arange(0,16).reshape(4,4)
print("Original array:\n",x)
print("\nExtracted data: Third and fourth elements of the first and second rows")
print(x[:2,2:])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [ ]:
### code here

In [89]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-07-01
Today:  2022-07-02
Tomorrow:  2022-07-03


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [ ]:
## code here

In [92]:
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))

First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
